---
- name: Install MySQL
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - mysql-server
    - mysql-client

- name: Start MySQL service
  become: yes
  service:
    name: mysql
    state: started
    enabled: yes

- name: Create MySQL database
  become: yes
  command: >
    mysql -uroot -p{{ mysql_root_password }} -e
    "CREATE DATABASE IF NOT EXISTS {{ mysql_db_name }};"

- name: Create MySQL user
  become: yes
  command: >
    mysql -uroot -p{{ mysql_root_password }} -e
    "CREATE USER '{{ mysql_db_user }}'@'localhost' IDENTIFIED BY '{{ mysql_db_password }}';"

- name: Grant privileges to MySQL user
  become: yes
  command: >
    mysql -uroot -p{{ mysql_root_password }} -e
    "GRANT ALL PRIVILEGES ON {{ mysql_db_name }}.* TO '{{ mysql_db_user }}'@'localhost';"

- name: Flush privileges
  become: yes
  command: >
    mysql -uroot -p{{ mysql_root_password }} -e "FLUSH PRIVILEGES;"

